source :rubygems
gem 'sinatra', '>=1.2.6'
gem 'sinatra-redis', '>=0.3.0'
gem 'haml', '>=3.1.2'
gem 'bcrypt-ruby', '>=3.0.0'
gem 'sass', '>=3.1.7'
gem 'json', '>=1.5.4'
gem 'hpricot', '>=0.8.4'
gem 'goodreads', :git => 'git://github.com/thegreatape/goodreads.git', :ref => '6f1b374'
gem 'oauth', '>=0.4.5'
gem 'resque'
gem 'resque-scheduler'
gem 'SystemTimer'
gem 'rack-test'

